// Exact country labels from sibling Discut frontend/src/app/components/flags.js.
// Keep values unchanged: Laravel stores the selected label in pays.
export const registrationCountries = [
  "Andorre",
  "Émirats arabes unis",
  "Afghanistan",
  "Antigua-et-Barbuda",
  "Anguilla",
  "Albanie",
  "Arménie",
  "Angola",
  "Antarctique",
  "Argentine",
  "Samoa américaines",
  "Autriche",
  "Australie",
  "Aruba",
  "Îles Åland",
  "Azerbaïdjan",
  "Bosnie-Herzégovine",
  "Barbade",
  "Bangladesh",
  "Belgique",
  "Burkina Faso",
  "Bulgarie",
  "Bahreïn",
  "Burundi",
  "Bénin",
  "Saint-Barthélemy",
  "Bermudes",
  "Brunei",
  "Bolivie",
  "Bonaire",
  "Brésil",
  "Bahamas",
  "Bhoutan",
  "Île Bouvet",
  "Botswana",
  "Biélorussie",
  "Belize",
  "Canada",
  "Îles Cocos",
  "République démocratique du Congo",
  "République centrafricaine",
  "République du Congo",
  "Suisse",
  "Côte d'Ivoire",
  "Îles Cook",
  "Chili",
  "Cameroun",
  "Chine",
  "Colombie",
  "Costa Rica",
  "Cuba",
  "Cap-Vert",
  "Curaçao",
  "Île Christmas",
  "Chypre",
  "République tchèque",
  "Allemagne",
  "Djibouti",
  "Danemark",
  "Dominique",
  "République dominicaine",
  "Algérie",
  "Équateur",
  "Estonie",
  "Égypte",
  "Sahara occidental",
  "Érythrée",
  "Espagne",
  "Éthiopie",
  "Union européenne",
  "Finlande",
  "Fidji",
  "Îles Malouines",
  "Micronésie",
  "Îles Féroé",
  "France",
  "Gabon",
  "Royaume-Uni",
  "Grenade",
  "Géorgie",
  "Guyane française",
  "Guernesey",
  "Ghana",
  "Gibraltar",
  "Groenland",
  "Gambie",
  "Guinée",
  "Guadeloupe",
  "Guinée équatoriale",
  "Grèce",
  "Géorgie du Sud",
  "Guatemala",
  "Guam",
  "Guinée-Bissau",
  "Guyana",
  "Hong Kong",
  "Îles Heard-et-MacDonald",
  "Honduras",
  "Croatie",
  "Haïti",
  "Hongrie",
  "Indonésie",
  "Irlande",
  "Île de Man",
  "Inde",
  "Territoire britannique de l'océan Indien",
  "Irak",
  "Iran",
  "Islande",
  "Italie",
  "Jersey",
  "Jamaïque",
  "Jordanie",
  "Japon",
  "Kenya",
  "Kirghizistan",
  "Cambodge",
  "Kiribati",
  "Comores",
  "Saint-Christophe-et-Niévès",
  "Corée du Nord",
  "Corée du Sud",
  "Koweït",
  "Îles Caïmans",
  "Kazakhstan",
  "Laos",
  "Liban",
  "Sainte-Lucie",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lesotho",
  "Lituanie",
  "Luxembourg",
  "Lettonie",
  "Libye",
  "Maroc",
  "Monaco",
  "Moldavie",
  "Monténégro",
  "Saint-Martin",
  "Madagascar",
  "Îles Marshall",
  "Macédoine du Nord",
  "Mali",
  "Myanmar",
  "Mongolie",
  "Macao",
  "Îles Mariannes du Nord",
  "Martinique",
  "Mauritanie",
  "Montserrat",
  "Malte",
  "Maurice",
  "Maldives",
  "Malawi",
  "Mexique",
  "Malaisie",
  "Mozambique",
  "Namibie",
  "Nouvelle-Calédonie",
  "Niger",
  "Île Norfolk",
  "Nigeria",
  "Nicaragua",
  "Pays-Bas",
  "Norvège",
  "Népal",
  "Nauru",
  "Niue",
  "Nouvelle-Zélande",
  "Oman",
  "Panama",
  "Pérou",
  "Polynésie française",
  "Papouasie-Nouvelle-Guinée",
  "Philippines",
  "Pakistan",
  "Pologne",
  "Saint-Pierre-et-Miquelon",
  "Îles Pitcairn",
  "Porto Rico",
  "Palestine",
  "Portugal",
  "Palaos",
  "Paraguay",
  "Qatar",
  "La Réunion",
  "Roumanie",
  "Serbie",
  "Russie",
  "Rwanda",
  "Arabie saoudite",
  "Îles Salomon",
  "Seychelles",
  "Soudan",
  "Suède",
  "Singapour",
  "Sainte-Hélène",
  "Slovénie",
  "Svalbard et Jan Mayen",
  "Slovaquie",
  "Sierra Leone",
  "Saint-Marin",
  "Sénégal",
  "Somalie",
  "Suriname",
  "Soudan du Sud",
  "Sao Tomé-et-Principe",
  "El Salvador",
  "Saint-Martin (partie néerlandaise)",
  "Syrie",
  "Eswatini",
  "Îles Turques-et-Caïques",
  "Tchad",
  "Terres australes françaises",
  "Togo",
  "Thaïlande",
  "Tadjikistan",
  "Tokelau",
  "Timor oriental",
  "Turkménistan",
  "Tunisie",
  "Tonga",
  "Turquie",
  "Trinité-et-Tobago",
  "Tuvalu",
  "Taïwan",
  "Tanzanie",
  "Ukraine",
  "Ouganda",
  "Îles mineures éloignées des États-Unis",
  "Nations Unies",
  "États-Unis",
  "Uruguay",
  "Ouzbékistan",
  "Vatican",
  "Saint-Vincent-et-les-Grenadines",
  "Venezuela",
  "Îles Vierges britanniques",
  "Îles Vierges américaines",
  "Vietnam",
  "Vanuatu",
  "Wallis-et-Futuna",
  "Samoa",
  "Kosovo",
  "Yémen",
  "Mayotte",
  "Afrique du Sud",
  "Zambie",
  "Zimbabwe",
] as const;

export const registrationCountrySet: ReadonlySet<string> = new Set(registrationCountries);
